--- 
id: basics
name: Remix 基础
summary: Remix基本操作流程
level: 1
tags: 
  - Remix
steps:
  - name: Remix 界面介绍 
    path: interface_introduction
  - name: 工作区 
    path: workspaces
  - name: Loading & Compiling
    path: load_and_compile
  - name: Deploying to the Remix VM
    path: deploy_to_the_remixvm
  - name: Interacting with Functions
    path: interacting
  - name: Deploying to Public Networks
    path: deploy_injected