--- 
id: er721Auction
name: NFT 拍卖合约
summary: 学习如何编写一个拍卖 ERC721 (NFT) 的智能合约. Developed by the p2p learning platform https://dacade.org.
level: 2
tags: 
  - Solidity
  - Tokens
  - NFT
steps:
  - name: Contract Setup 
    path: auction-contract-setup
  - name: Start and Bid Functions
    path: auction-start-bid
  - name: Withdraw and End Functions
    path: auction-withdraw-end